name: Generate Snake

on:
  schedule:
    - cron: "0 */6 * * *"  # every 6 hours
  workflow_dispatch:
  push:
    branches:
      - main
      - master

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      - name: Generate snake.svg
        uses: Platane/snk/svg-only@v2
        with:
          github_user_name: ReeKarbit
          outputs: |
            dist/snake.svg
            dist/snake-dark.svg?palette=github-dark&color_snake=orange
            dist/snake-light.svg?palette=github-light&color_snake=green

      - name: Push snake.svg to output branch
        uses: crazy-max/ghaction-github-pages@v2.6.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
